version: '3.9'

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: despesa_certa
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "55432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d despesa_certa"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  backend:
    build: .
    command: gunicorn backend_expenses.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env.docker
    environment:
      - RUNNING_IN_DOCKER=1
      - DJANGO_SETTINGS_MODULE=backend_expenses.settings.local
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  worker:
    build: .
    command: celery -A backend_expenses worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env.docker
    environment:
      - RUNNING_IN_DOCKER=1
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

volumes:
  pgdata:
